set tw=0
set ai
set ci
set ts=4
set sw=4
set noet

" Include Syntax Files
source /usr/share/vim/addons/syntax/gnomedesktop.vim
source /usr/share/vim/addons/syntax/cairo.vim
source /usr/share/vim/addons/syntax/libglade.vim
source /usr/share/vim/addons/syntax/xlib.vim
source /usr/share/vim/addons/syntax/pango.vim
source /usr/share/vim/addons/syntax/clutter.vim
source /usr/share/vim/addons/syntax/liboil.vim
source /usr/share/vim/addons/syntax/gdk.vim
source /usr/share/vim/addons/syntax/gtk.vim
source /usr/share/vim/addons/syntax/gail.vim
source /usr/share/vim/addons/syntax/libsoup.vim
source /usr/share/vim/addons/syntax/libgnomeui.vim
source /usr/share/vim/addons/syntax/libgnome.vim
source /usr/share/vim/addons/syntax/goocanvas.vim
source /usr/share/vim/addons/syntax/librsvg.vim
source /usr/share/vim/addons/syntax/libgsf.vim
source /usr/share/vim/addons/syntax/gconf.vim
source /usr/share/vim/addons/syntax/libunique.vim
source /usr/share/vim/addons/syntax/gobject.vim
source /usr/share/vim/addons/syntax/atk.vim
source /usr/share/vim/addons/syntax/gio.vim
source /usr/share/vim/addons/syntax/evince.vim
source /usr/share/vim/addons/syntax/orbit2.vim
source /usr/share/vim/addons/syntax/gtkglext.vim
source /usr/share/vim/addons/syntax/gimp.vim
source /usr/share/vim/addons/syntax/gdkpixbuf.vim
source /usr/share/vim/addons/syntax/libgnomecanvas.vim
source /usr/share/vim/addons/syntax/gtksourceview.vim
source /usr/share/vim/addons/syntax/glib.vim
source /usr/share/vim/addons/syntax/dbusglib.vim
source /usr/share/vim/addons/syntax/gnomevfs.vim
source /usr/share/vim/addons/syntax/libnotify.vim
source /usr/share/vim/addons/syntax/poppler.vim
source /usr/share/vim/addons/syntax/libwnck.vim
source /usr/share/vim/addons/syntax/vte.vim
source /usr/share/vim/addons/syntax/atspi.vim

